#pragma once

using namespace ATL;

template <class T>
class CProxy_IBrowserAppEvents : public IConnectionPointImpl<T, &__uuidof(_IBrowserAppEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
