#pragma once

using namespace ATL;

template <class T>
class CProxy_IBrowserEvents : public IConnectionPointImpl<T, &__uuidof( _IBrowserEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
